-- Get the total number of clients by status
SELECT Status, COUNT(*) AS ClientCount
FROM Clients
GROUP BY Status;

-- Get the total fees earned by each service
SELECT s.ServiceType, SUM(p.Fee) AS TotalFee
FROM Projects p
JOIN Services s ON p.ServiceID = s.ServiceID
GROUP BY s.ServiceType;

-- Get the number of projects each consultant is assigned to
SELECT c.ConsultantName, COUNT(pa.ProjectID) AS ProjectsAssigned
FROM Consultants c
LEFT JOIN Project_Assignments pa ON c.ConsultantID = pa.ConsultantID
GROUP BY c.ConsultantName;

-- Get the total hours worked by each consultant
SELECT c.ConsultantName, SUM(pa.HoursWorked) AS TotalHoursWorked
FROM Consultants c
LEFT JOIN Project_Assignments pa ON c.ConsultantID = pa.ConsultantID
GROUP BY c.ConsultantName;

-- Get the number of projects each client has
SELECT cl.ClientName, COUNT(p.ProjectID) AS ProjectsCount
FROM Clients cl
LEFT JOIN Projects p ON cl.ClientID = p.ClientID
GROUP BY cl.ClientName;

-- Get the total unpaid invoice amounts for each client
SELECT cl.ClientName, SUM(i.Amount) AS TotalUnpaidAmount
FROM Clients cl
JOIN Projects p ON cl.ClientID = p.ClientID
JOIN Invoices i ON p.ProjectID = i.ProjectID
WHERE i.Status = 'Unpaid'
GROUP BY cl.ClientName;

-- Get the most expensive project
SELECT p.ProjectName, p.Fee
FROM Projects p
ORDER BY p.Fee DESC
LIMIT 1;

-- Get the number of active consultants in each specialty
SELECT c.Specialty, COUNT(*) AS ActiveConsultants
FROM Consultants c
WHERE c.Status = 'Available'
GROUP BY c.Specialty;

-- Get the services that have the highest average fee
SELECT s.ServiceType, AVG(p.Fee) AS AvgFee
FROM Projects p
JOIN Services s ON p.ServiceID = s.ServiceID
GROUP BY s.ServiceType
ORDER BY AvgFee DESC
LIMIT 1;

-- Get the total revenue generated by each project
SELECT p.ProjectName, SUM(i.Amount) AS TotalRevenue
FROM Projects p
JOIN Invoices i ON p.ProjectID = i.ProjectID
GROUP BY p.ProjectName;

-- Get the most recent project for each client
SELECT cl.ClientName, p.ProjectName, p.StartDate
FROM Clients cl
JOIN Projects p ON cl.ClientID = p.ClientID
WHERE p.StartDate = (
    SELECT MAX(p2.StartDate)
    FROM Projects p2
    WHERE p2.ClientID = cl.ClientID
);

-- Get the number of consultants assigned to each project
SELECT p.ProjectName, COUNT(pa.ConsultantID) AS ConsultantsAssigned
FROM Projects p
LEFT JOIN Project_Assignments pa ON p.ProjectID = pa.ProjectID
GROUP BY p.ProjectName;

-- Get the total hours worked per project
SELECT p.ProjectName, SUM(pa.HoursWorked) AS TotalHours
FROM Projects p
JOIN Project_Assignments pa ON p.ProjectID = pa.ProjectID
GROUP BY p.ProjectName;